site_name: Jeeves
theme: readthedocs
nav:
  - index.md
  - setup-application.md
  - install-jenkins.md
  - configure-jenkins.md
markdown_extensions:
  - markdown.extensions.admonition
repo_url: https://github.com/modess/jeeves/
edit_uri: edit/gh-pages/docs/
